// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvxFDv2IhEnL-wu61Y7DVvqOhZaDI9ry4',
    appId: '1:993143533301:web:d47d2c54432a666c709fbc',
    messagingSenderId: '993143533301',
    projectId: 'socialmediaapp-96890',
    authDomain: 'socialmediaapp-96890.firebaseapp.com',
    storageBucket: 'socialmediaapp-96890.firebasestorage.app',
    measurementId: 'G-THC7M2EV0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqLB9iKfL7cQjZK-cTosZkngrLJuyarJs',
    appId: '1:993143533301:android:5c0ece8b9a77a62a709fbc',
    messagingSenderId: '993143533301',
    projectId: 'socialmediaapp-96890',
    storageBucket: 'socialmediaapp-96890.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDR5IG-HL4oEscKMRfgz6pI5anRqqMhAc',
    appId: '1:993143533301:ios:073176ee299dcaad709fbc',
    messagingSenderId: '993143533301',
    projectId: 'socialmediaapp-96890',
    storageBucket: 'socialmediaapp-96890.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
